openapi: 3.0.0
info:
  contact:
    name: COINAPI LTD
    url: https://www.coinapi.io
  description: |
    This section will provide necessary information about the `CoinAPI OEML REST API` protocol.
  license:
    name: MIT
    url: https://github.com/coinapi/coinapi-sdk/blob/master/LICENSE
  title: OEML - REST API
  version: v1
servers:
- url: http://localhost:8080
tags:
- description: |
    Order statuses and the lifecycle are documented in the separate section: <a href="#oeml-order-lifecycle">OEML / Starter Guide / Order Lifecycle</a>
  name: Orders
- name: Balances
- name: Positions
paths:
  /v1/orders:
    get:
      description: Get all current open orders across all or single specified exchange.
      parameters:
      - description: Filter the output to the orders from the specific exchange.
        explode: true
        in: query
        name: exchange_id
        required: false
        schema:
          example: KRAKEN
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orders'
          description: Collection of requested open orders.
      summary: Get all orders
      tags:
      - Orders
    post:
      description: This request creating new order for the specific exchange.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewOrderSingle'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionReport'
          description: Created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: Validation errors
        "490":
          content:
            appliction/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: Exchange not registered
      summary: Create new order
      tags:
      - Orders
  /v1/orders/status/{client_order_id}:
    get:
      description: Get the current order status for the specified order. The requested
        order can no longer be active.
      parameters:
      - description: Order Client Id of the order for which the status is requested.
        explode: false
        in: path
        name: client_order_id
        required: true
        schema:
          example: 6ab36bc1-344d-432e-ac6d-0bf44ee64c2b
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionReport'
          description: The order was found.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: The order was not found.
      summary: Get order status
      tags:
      - Orders
  /v1/orders/cancel:
    post:
      description: This request cancels an existing order. The order can be canceled
        by the client order ID or exchange order ID.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCancelSingleRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionReport'
          description: Canceled order
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: Validation errors
        "490":
          content:
            appliction/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: Exchange not registered
      summary: Cancel order
      tags:
      - Orders
  /v1/orders/cancel/all:
    post:
      description: This request cancels all open orders across all or single specified
        exchange.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCancelAllRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: Result
      summary: Cancel all orders
      tags:
      - Orders
  /v1/balances:
    get:
      description: Returns all of your balances, including available balance.
      parameters:
      - description: Exchange name
        explode: true
        in: query
        name: exchange_id
        required: false
        schema:
          example: KRAKEN
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balances'
          description: Result
      summary: Get balances
      tags:
      - Balances
  /v1/positions:
    get:
      description: Returns all of your positions.
      parameters:
      - description: Exchange name
        explode: true
        in: query
        name: exchange_id
        required: false
        schema:
          example: KRAKEN
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Positions'
          description: Result
      summary: Get positions
      tags:
      - Positions
components:
  schemas:
    Orders:
      description: Collection of currently opened orders.
      items:
        $ref: '#/components/schemas/ExecutionReport'
      type: array
    NewOrderSingle:
      description: The new order message.
      example:
        symbol_coinapi: KRAKEN_SPOT_BTC_USD
        exchange_id: KRAKEN
        client_order_id: KPP-222389382-AQ
        side: BUY
        time_in_force: GOOD_TILL_CANCEL
        price: 0.0783
        amount_order: 0.045
        expire_time: ""
        exec_inst: MAKER_OR_CANCEL
        order_type: LIMIT
        symbol_exchange: BTCUSD
      properties:
        exchange_id:
          description: Exchange identifier.
          example: KRAKEN
          type: string
        client_order_id:
          description: Unique identifier for the order assigned by the `OEML API`
            client.
          example: KPP-222389382-AQ
          type: string
        symbol_exchange:
          description: Exchange symbol. One of the properties (`symbol_exchange`,
            `symbol_coinapi`) is required to identify the market for the order.
          example: BTCUSD
          type: string
        symbol_coinapi:
          description: CoinAPI symbol. One of the properties (`symbol_exchange`, `symbol_coinapi`)
            is required to identify the market for the order.
          example: KRAKEN_SPOT_BTC_USD
          type: string
        amount_order:
          description: Order quantity.
          example: 0.045
          type: number
        price:
          description: Order price.
          example: 0.0783
          type: number
        side:
          $ref: '#/components/schemas/OrdSide'
        order_type:
          $ref: '#/components/schemas/OrdType'
        time_in_force:
          $ref: '#/components/schemas/TimeInForce'
        expire_time:
          description: Expiration time. Conditionaly required for orders with time_in_force
            = `GOOD_TILL_TIME_EXCHANGE` or `GOOD_TILL_TIME_OEML`.
          type: date
        exec_inst:
          description: 'Order execution instructions are documented in the separate
            section: <a href="#oeml-order-params-exec">OEML / Starter Guide / Order
            parameters / Execution instructions</a>'
          example: MAKER_OR_CANCEL
          items:
            enum:
            - MAKER_OR_CANCEL
            - AUCTION_ONLY
            - INDICATION_OF_INTEREST
            type: string
          type: array
      required:
      - amount_order
      - client_order_id
      - exchange_id
      - order_type
      - price
      - side
      - time_in_force
      type: object
    ExecutionReport:
      allOf:
      - $ref: '#/components/schemas/NewOrderSingle'
      - $ref: '#/components/schemas/ExecutionReport_allOf'
    OrderCancelSingleRequest:
      example:
        exchange_id: KRAKEN
        client_order_id: A12345
        exchange_order_id: d8574207d9e3b16a4a5511753eeef1751
      properties:
        exchange_id:
          description: Exchange name
          example: KRAKEN
          type: string
        exchange_order_id:
          description: Order Id
          example: d8574207d9e3b16a4a5511753eeef1751
          type: string
        client_order_id:
          description: Client order Id
          example: A12345
          type: string
      type: object
    OrderCancelAllRequest:
      example:
        exchange_id: KRAKEN
      properties:
        exchange_id:
          description: Exchange identifier from which active orders should be canceled.
          example: KRAKEN
          type: string
      required:
      - exchange_id
      type: object
    Balances:
      items:
        $ref: '#/components/schemas/Balance'
      type: array
    Balance:
      example:
        exchange_name: KRAKEN
        data:
        - symbol_coinapi: BTC
          update_origin: EXCHANGE
          balance: 0.00134444
          available: 0.00134444
          id: BTC
          locked: 0.0
          symbol_exchange: BTC
        - symbol_coinapi: BTC
          update_origin: EXCHANGE
          balance: 0.00134444
          available: 0.00134444
          id: BTC
          locked: 0.0
          symbol_exchange: BTC
        type: snapshotBalances
      properties:
        type:
          description: Result type.
          example: snapshotBalances
          type: string
        exchange_name:
          description: Exchange name.
          example: KRAKEN
          type: string
        data:
          items:
            $ref: '#/components/schemas/Balance_data'
          type: array
      type: object
    Positions:
      items:
        $ref: '#/components/schemas/Position'
      type: array
    Position:
      example:
        exchange_name: KRAKEN
        data:
        - liquidation_price: 0.072323
          symbol_coinapi: BTC
          leverage: 0.0
          unrealised_pn_l: 0.0
          quantity: 0.00134444
          cross_margin: true
          id: 2873jkjhgdsd78ii
          raw_data: xyz
          symbol_exchange: BTC
          avg_entry_price: 0.00134444
          is_buy: true
        - liquidation_price: 0.072323
          symbol_coinapi: BTC
          leverage: 0.0
          unrealised_pn_l: 0.0
          quantity: 0.00134444
          cross_margin: true
          id: 2873jkjhgdsd78ii
          raw_data: xyz
          symbol_exchange: BTC
          avg_entry_price: 0.00134444
          is_buy: true
        type: snapshotPositions
      properties:
        type:
          description: Result type.
          example: snapshotPositions
          type: string
        exchange_name:
          description: Name of exchange.
          example: KRAKEN
          type: string
        data:
          items:
            $ref: '#/components/schemas/Position_data'
          type: array
      type: object
    ValidationError:
      properties:
        type:
          example: https://tools.ietf.org/html/rfc7231#section-6.5.1
          type: string
        title:
          example: One or more validation errors occurred.
          type: string
        status:
          example: 400
          type: number
        traceId:
          example: d200e8b5-4271a5461ce5342f
          type: string
        errors:
          type: string
      title: JSON validation error.
      type: object
    Message:
      example:
        exchange_id: KRAKEN
        type: message
        message: Ok
      properties:
        type:
          description: Type of message.
          example: message
          type: string
        severity:
          $ref: '#/components/schemas/Severity'
        exchange_id:
          description: If message related exchange then identifier of this exchange.
          example: KRAKEN
          type: string
        message:
          description: Sucess message
          example: Ok
          type: string
      title: Success or error message carrier.
      type: object
    Severity:
      enum:
      - INFO
      - WARNING
      - ERROR
      type: string
    OrdStatus:
      description: |
        Order statuses and the lifecycle are documented in the separate section: <a href="#oeml-order-lifecycle">OEML / Starter Guide / Order Lifecycle</a>
      enum:
      - RECEIVED
      - ROUTING
      - ROUTED
      - NEW
      - PENDING_CANCEL
      - PARTIALLY_FILLED
      - FILLED
      - CANCELED
      - REJECTED
      type: string
    OrdSide:
      description: |
        Side of order.
      enum:
      - BUY
      - SELL
      example: BUY
      type: string
    OrdType:
      description: |
        Order types are documented in the separate section: <a href="#oeml-order-params-type">OEML / Starter Guide / Order parameters / Order type</a>
      enum:
      - LIMIT
      example: LIMIT
      type: string
    TimeInForce:
      description: |
        Order time in force options are documented in the separate section: <a href="#oeml-order-params-tif">OEML / Starter Guide / Order parameters / Time in force</a>
      enum:
      - GOOD_TILL_CANCEL
      - GOOD_TILL_TIME_EXCHANGE
      - GOOD_TILL_TIME_OMS
      - FILL_OR_KILL
      - IMMEDIATE_OR_CANCEL
      example: GOOD_TILL_CANCEL
      type: string
    ExecInst:
      description: 'Order execution instructions are documented in the separate section:
        <a href="#oeml-order-params-exec">OEML / Starter Guide / Order parameters
        / Execution instructions</a>'
      example: MAKER_OR_CANCEL
      items:
        enum:
        - MAKER_OR_CANCEL
        - AUCTION_ONLY
        - INDICATION_OF_INTEREST
        type: string
      type: array
    ExecutionReport_allOf:
      description: The order execution report message.
      properties:
        client_order_id_format_exchange:
          description: Hash client id
          example: f81211e2-27c4-b86a-8143-01088ba9222c
          type: string
        exchange_order_id:
          description: Exchange order id
          example: 90832ASASAS89789-1112
          type: string
        amount_open:
          description: Amount open
          example: 0.22
          type: number
        amount_filled:
          description: Amount filled
          example: 0.0
          type: number
        status:
          $ref: '#/components/schemas/OrdStatus'
        time_order:
          description: Timestamped history of order status changes.
          items:
            items:
              example: '[["RECEIVED","2020-05-27T11:16:20.1677709Z"],["REJECTED","2020-05-27T11:16:20.1677710Z"]]'
              type: string
            type: array
          type: array
        error_message:
          description: Error message
          example: '{"result":"error","reason":"InsufficientFunds","message":"Failed
            to place buy order on symbol ''BTCUSD'' for price $7,000.00 and quantity
            0.22 BTC due to insufficient funds"}'
          type: string
      required:
      - amount_filled
      - amount_open
      - client_order_id_format_exchange
      - status
      - time_order
    Balance_data:
      example:
        symbol_coinapi: BTC
        update_origin: EXCHANGE
        balance: 0.00134444
        available: 0.00134444
        id: BTC
        locked: 0.0
        symbol_exchange: BTC
      properties:
        id:
          description: Exchange identifier.
          example: BTC
          type: string
        symbol_exchange:
          description: Exchange currency code.
          example: BTC
          type: string
        symbol_coinapi:
          description: CoinAPI currency code.
          example: BTC
          type: string
        balance:
          description: Value of the current total currency balance on the exchange.
          example: 0.00134444
          format: float
          type: number
        available:
          description: Value of the current available currency balance on the exchange
            that can be used as collateral.
          example: 0.00134444
          format: float
          type: number
        locked:
          description: Value of the current locked currency balance by the exchange.
          example: 0.0
          format: float
          type: number
        update_origin:
          description: |
            Source of the last modification.
          enum:
          - INITIALIZATION
          - BALANCE_MANAGER
          - EXCHANGE
          example: EXCHANGE
          type: string
    Position_data:
      example:
        liquidation_price: 0.072323
        symbol_coinapi: BTC
        leverage: 0.0
        unrealised_pn_l: 0.0
        quantity: 0.00134444
        cross_margin: true
        id: 2873jkjhgdsd78ii
        raw_data: xyz
        symbol_exchange: BTC
        avg_entry_price: 0.00134444
        is_buy: true
      properties:
        id:
          description: Unique position ID
          example: 2873jkjhgdsd78ii
          type: string
        symbol_exchange:
          description: The contract for this position.
          example: BTC
          type: string
        symbol_coinapi:
          description: The coinapi contract for this position.
          example: BTC
          type: string
        avg_entry_price:
          example: 0.00134444
          type: number
        quantity:
          description: The current position amount in contracts.
          example: 0.00134444
          type: number
        is_buy:
          example: true
          type: boolean
        unrealised_pn_l:
          description: Unrealised PNL is all the unrealised profit or loss coming
            from your portfolio's open positions.
          example: 0.0
          type: number
        leverage:
          description: 1 / initMarginReq.
          example: 0.0
          type: number
        cross_margin:
          description: True/false depending on whether you set cross margin on this
            position.
          example: true
          type: boolean
        liquidation_price:
          description: Once markPrice reaches this price, this position will be liquidated.
          example: 0.072323
          type: number
        raw_data:
          example: xyz
          type: string
